version: "3"
services:
  web:
    build: .
    container_name: container-aplicacao
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./app:/usr/app
      - /usr/app/node_modules
    environment:
      DATABASE_URL: mysql://docker:docker@db:3306/banco
  db:
    container_name: container-mysql
    image: mysql:5.7
    volumes:
      - ./mysql-data/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
