apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    -
      name: container-mysql
      image: mysql:5.7
      ports:
        - containerPort: 3306
      env:
        -
          name: MYSQL_ROOT_PASSWORD
          value: root
        -
          name: MYSQL_DATABASE
          value: banco
        -
          name: MYSQL_USER
          value: docker
        -
          name: MYSQL_PASSWORD
          value: docker
