apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: statefulset-mysql
spec:
  serviceName: db
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
        -
          name: container-mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            -
              name: MYSQL_ROOT_PASSWORD
              value: root
            -
              name: MYSQL_DATABASE
              value: banco
            -
              name: MYSQL_USER
              value: docker
            -
              name: MYSQL_PASSWORD
              value: docker
          volumeMounts:
            -
              name: mysql-data
              mountPath: /var/lib/mysql
            -
              name: mysql-config-volume
              mountPath: /etc/mysql/conf.d/default_auth.cnf
              subPath: default_auth
      volumes:
        -
          name: mysql-data
          persistentVolumeClaim:
            claimName: configuracao-mysql
        -
          name: mysql-config-volume
          configMap:
            name: mysql-config
